### ISSUE TITLE
Paper link?

### ISSUE THREAD

**Issue by zhanqan** [MikeLagunes/Supervised-Triplet-Network#1]
I'm really interested in your marvelous implementation of this paper. However, i haven't found this paper, can you provide this paper for me? Hope for your reply! Thanks a lot!

**Comment by MikeLagunes** [comment]
Hello Zhanqan,

Glad to hear our paper will be useful for you. It will be published around
May in ICRA 2019, but I can share with you our paper from here. I'll put
the official link and citation on GitHub around those days,

Cheers,


Mike
